# This is a basic workflow to help you get started with Actions
name: wikijs-start

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  start-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Aws Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.WIKIJS_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.WIKIJS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Start ec2 instance
        env:
          INSTANCE_ID: ${{ secrets.WIKIJS_EC2_INSTANCE_ID }}
        run: |
          aws ec2 start-instances --instance-id $INSTANCE_ID
      - name: Wait for ec2 instance state update
        run: sleep 5
      - name: Upsert route53 record
        env:
          INSTANCE_ID: ${{ secrets.WIKIJS_EC2_INSTANCE_ID }}
          HOSTED_ZONE_ID: ${{ secrets.WIKIJS_HOSTED_ZONE_ID }}
        run: |
          AWS_PAGER='' aws ec2 describe-instances --instance-id $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicDnsName' --output text | read CNAME_VALUE
          echo $CNAME_VALUE
          cat base-files/wiki/route53-change-record.json
          sed "s/#CNAME_VALUE/$CNAME_VALUE/g" base-files/wiki/route53-change-record.json > route53-change-record.json
          cat route53-change-record.json
          aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --change-batch file://route53-change-record.json
