# This is a basic workflow to help you get started with Actions
name: wikijs-stop

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '15 12 * * *'  # every day at 9:15pm JST

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  stop-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Aws Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.WIKIJS_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.WIKIJS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Stop ec2 instance
        env:
          INSTANCE_ID: ${{ secrets.WIKIJS_EC2_INSTANCE_ID }}
        run: |
          aws ec2 stop-instances --instance-id $INSTANCE_ID
